--AULA 08 - BETWEEN aos 46:27 do video
--BETWEEN É USADO PARA SE ENCONTRAR UM VALOR "ENTRE" UM VALOR MÍNIMO E UM VALOR MÁXIMO INFORMADOS

SELECT *
	FROM Production.Product
	WHERE ListPrice BETWEEN 1000 AND 1500		--valor BETWEEN mínimo AND máximo
	ORDER BY ListPrice;

SELECT *
	FROM Production.Product
	WHERE ListPrice NOT BETWEEN 1000 AND 1500	--NOT BETWEEN = TRAZ TUDO COM EXERCEÇÃO DO RANGE PASSADO AO BETWEEN
	ORDER BY ListPrice;
