--AULA 11 - DESAFIOS FUNDAMENTOS SQL aos 1:01:06 do video

--1 DESAFIO: QUANTOS PRODUTOS CUSTAM + QUE $1500
SELECT COUNT(ListPrice) AS 'PRODUTOS QUE CUSTAM + DE $1500'
	FROM Production.Product
	WHERE ListPrice > 1500;

--2 DESAFIO: QUANTAS PESSOAS QUE INICIAM O SOBRENOME COM "P"
SELECT COUNT(LastName) AS 'PESSOAS QUE INICIAM O SOBRENOME COM "P"'
	FROM Person.Person
	WHERE LastName LIKE 'P%';

--3 DESAFIO: QUANTAS CIDADES ÚNICAS ESTÃO CADASTRADOS NOSSO CLIENTES
SELECT COUNT(DISTINCT City) AS 'CIDADES ÚNICAS CADASTRADAS'
	FROM Person.Address;

--4 DESAFIO: QUAIS SÃO AS CIDADES ÚNICAS ESTÃO CADASTRADOS NO SISTEMA
SELECT DISTINCT City
	FROM Person.Address;

--5 DESAFIO: QUANTOS PRODUTOS VERMELHOS COM PREÇO ENTRE $500 A $1000
SELECT COUNT(*) AS 'PRODUTOS VERMELHOS COM PREÇO ENTRE $500 A $1000'
	FROM Production.Product
	WHERE Color = 'Red'
	AND ListPrice BETWEEN 500 AND 1000;

--6 DESAFIO: QUANTOS PRODUTOS QUE TEM A PALAVRA "road" NO NOME
SELECT COUNT(*) AS 'PRODUTOS QUE TEM A PALAVRA "road" NO NOME'
	FROM Production.Product
	WHERE Name LIKE '%ROAD%';
