--AULA 10 - LIKE aos 55:40 do video
--INFORMAMOS AO LIKE UM PEDAÇO DA INFORMA(NOME POR EXEMPLO) QUE SÓ LEMBRAMOS UMA PARTE E ELE RETORNA OS DADOS QUE CONTÉM ESSA PARTE INFORMADA

SELECT *
	FROM Person.Person
	WHERE FirstName LIKE '%ro';		
	--1 EX: O ' % ' INFORMA A PARTE QUE NÃO SE LEMBRA, NESSE EXEMPLO RETORNARÁ NOME TERMINADO EM "ro"

SELECT *
	FROM Person.Person
	WHERE FirstName LIKE '%ro__';
	--2 EX: O ' _ ' SUBSTITUI TAMBÉM OS CAMPOS POR LETRAS QUE NÃO SE LEMBRA, NESSE EXEMPLO RETORNARÁ NOME QUE TEM MAIS 2 LETRAS APÓS O "ro"

SELECT *
	FROM Person.Person
	WHERE FirstName LIKE 'RO%';
	--3 EX: O CONTRARIO DO "1 EX" ACIMA, NESSE EXEMPLO RETORNARÁ NOME COMEÇADO EM "ro"
