--AULA 12 - MIN MAX SUM AVG aos 1:06:40 do video

--MIN = MÍNIMO, TRAZ O MENOR VALOR ENCONTRADO NOS DADOS
SELECT TOP 10 MIN(LineTotal) AS 'MENOR VALOR ENCONTRADO'
	FROM Sales.SalesOrderDetail;

--MAX = MÁXIMO, TRAZ O MAIOR VALOR ENCONTRADO NOS DADOS
SELECT TOP 10 MAX(LineTotal) AS 'MAIOR VALOR ENCONTRADO'
	FROM Sales.SalesOrderDetail;

--SUM = SOMA, TRAZ A SOMA DE TODOS OS VALORES ENCONTRADO NOS DADOS
SELECT TOP 10 SUM(LineTotal) AS 'SOMA DE TODOS OS VALORES'
	FROM Sales.SalesOrderDetail;

--AVG = MÉDIA, TRAZ A MÉDIA DE TODOS OS VALORES ENCONTRADO NOS DADOS
SELECT TOP 10 AVG(LineTotal) AS 'MÉDIA DE TODOS OS VALORES'
	FROM Sales.SalesOrderDetail;
