--"AULA 05" - COUNT + DESAFIOS aos 34:10 do video --> ESTÁ DENTRO DA "AULA 04 - WHERE" NA LISTA DO VIDEO

--DESAFIO 1
SELECT COUNT(ProductID) AS 'TOTAL DE PRODUTOS'
	FROM Production.Product;

--DESAFIO 2
SELECT COUNT(Size) AS 'PRODUTOS COM TAMANHOS'
	FROM Production.Product;

/*
--DESAFIO 3
SELECT COUNT(DISTINCT Size) AS 'TAMANHOS CADASTRADOS'
	FROM Production.Product
	WHERE Size <> 'NULL';
*/