--AULA 04 - COUNT + DESAFIOS aos 34:10 do video

--DESAFIO 1
SELECT COUNT(ProductID) AS 'TOTAL DE PRODUTOS'
	FROM Production.Product;

--DESAFIO 2
SELECT COUNT(Size) AS 'PRODUTOS COM TAMANHOS'
	FROM Production.Product;

/*
--DESAFIO 3
SELECT COUNT(DISTINCT Size) AS 'TAMANHOS CADASTRADOS'
	FROM Production.Product
	WHERE Size <> 'NULL';
*/