--AULA 07 - ORDER BY + DESAFIOS aos 40:00 do video
--ORDER BY = ORDERNAR POR;		ASC = CRESCENTE;	DESC = DECRESCENTE

--DESAFIO 1 - OBTER O 'ProductID' DOS  10 PRODUTOS + CAROS CADASTROS NO SISTEMA
SELECT TOP 10 ProductID AS 'TOP 10 PRODUTOS + CAROS'
	FROM Production.Product
	ORDER BY ListPrice DESC;

--DESAFIO 2 - OBTER O 'NOME' E 'NUMERO DO PRODUTO' DOS PRODUTOS QUE TEM O 'ProductID' ENTRE 1 E  4
SELECT TOP 4 ProductID, Name, ProductNumber
	FROM Production.Product
	ORDER BY ProductID ASC;